clone_folder: C:\M

environment:
    DEPLOY_PROVIDER: bintray
    BINTRAY_ACCOUNT: reznikmm
    BINTRAY_REPOSITORY: msys2
    PACMAN_REPOSITORY_NAME: ci.mingw
    BUILD_URL: https://ci.appveyor.com/project/$(APPVEYOR_ACCOUNT_NAME)/$(APPVEYOR_PROJECT_NAME)/build/$(APPVEYOR_BUILD_VERSION)

build_script:
    - echo [ci.mingw] >> c:\msys64\etc\pacman.conf
    - echo SigLevel = Optional >> c:\msys64\etc\pacman.conf
    - echo Server = https://dl.bintray.com/reznikmm/msys2/ >> c:\msys64\etc\pacman.conf
    - C:\msys64\usr\bin\pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade
    - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci-build.sh"

artifacts:
    - path: artifacts\*

deploy:
    - provider: BinTray
      username: $(BINTRAY_ACCOUNT)
      subject: $(BINTRAY_ACCOUNT)
      repo: $(BINTRAY_REPOSITORY)
      package: $(PACMAN_REPOSITORY_NAME)
      version: latest
      publish: true
      override: true
      api_key:
          secure: X/cCmD5VsmLoO6lnB086Lrc3+Zx5WIriImHgqrwrwO4/fyQ7sOZKieYuph85lh+4
